### ISSUE TITLE
Fix the tiny gap under replaced elements that shows by default

### ISSUE THREAD

**Issue by jensimmons** [mozdevs/cssremedy#14]
I was just reading Tantek's original [Reset stylesheet](http://tantek.com/log/2004/undohtml.css) (likely the first ever).

He wrote
```
/* whoever thought blue linked image borders were a good idea? */
a img,:link img,:visited img { border:none }
```

OMG! That's right. There were ugly blue boxes around images that have a link. Does this still happen anyplace? I don't think so. But if it does.... we should fix it. Ha.

Meanwhile, I do think images still have that little gap below them, because they are `display: inline` by default (mistake, imho), and the line height for whatever text size is added to the bottom of the box. I've spent many hours of my life trying to figure out where that gap is coming from. Until I finally remembered to always include this in my CSS:
```
img { display: block; }
```

Shall we add that to Remedy? Does anyone else always do this?

**Comment by danburzo** [comment]
There was someone talking on Twitter a while ago about `display: block` on images as "treating a symptom", and offered an intentional solution to removing the gap... but I can't find it right now, will get back when I do!

**Comment by jensimmons** [comment]
I just made a demo: https://codepen.io/jensimmons/pen/QYmmJK?editors=1100
You can see it on a page by itself (link might expire): https://s.codepen.io/jensimmons/debug/QYmmJK

**Comment by jensimmons** [comment]
I feel like `vertical-align: middle` changes the default too much — gets into a world where images could end up in unexpected places. 

@fantasai [concurs](https://twitter.com/fantasai/status/1093270779951628288):
>Honestly if you're not using an image as part of an inline layout, display: block makes perfect sense. Also 'middle' is a weird value, I'd pick top or bottom, neither of which invokes alignment to font metrics.

All of this does depend on the image. If it's a little icon, like the demo on the [MDN page for vertical align](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align), then `vertical-align: middle` is what you want. 

After looking at this again for a while, I believe we have two choices.
```
img {
    display: block;
}
```
or
```
img {
   vertical-align: bottom;
}
```

Neither gives people their likely desired result for little inline icon images. Developers are going to need to write code for those usecases. There's simply too much variation in such moments to be able to guess what people want. 

To me, this is a choice between 
1) Set people up for the thing they are doing most often — using images as blocks. 
or
2) Stay as close as possible to the default CSS, keeping images inline, adjusting vertical-align to bottom in order to remove the mystery line spacing. That's Benjamin's argument in the tweet he wrote (referenced above, thanks @danburzo for bringing it up) — don't change CSS more than you mean to, just fix the bug you have. 

To me, this isn't about correcting a bug, however. This is about finding a new best default. I expect that someone long ago debated whether to make images behave as (what we now call) inline or block. Maybe there was a public discussion. Maybe Marc Andreessen [just decided](https://thehistoryoftheweb.com/the-origin-of-the-img-tag/). But if we were inventing the img element and its default CSS today, for the first time, I believe it would make more sense to set the default to block. My sense is that most of the time, images are in fact presented as a block-type object. The usecase where an image is set within a line of type — as _part_ of that line of type — maybe we do that 10% of the time? This makes me lean towards:
```
img {
   display: block;
}
```

**Comment by tigt** [comment]
Twitter and WordPress use inline `<img>` for emoji — devices without the right fonts, new emoji that keep getting released, etc. Then there's the older phpBB/other forum software smileys, and so on.

Firefox's reader mode has problems with them as a result of it trying to blockify images, so I would heavily recommend keeping images inline. Blockifying images works pretty naturally like this already:

```html
<p>Blah blah blah…</p>

<img>

<p>Bloo bloo bloo…</p>
```

…which seems to be the simplest thing that could possibly work, markup-wise.

**Comment by mor10** [comment]
As I understand it, based on the original spec, the img element was meant to display inline icons and figures, much like how emoji are displayed inline today. However, this is not the "normal" use case for the img element today, nor has it been for a very long time. Imo the img element should be block level, and the developer can choose to set display:inline in the rare cases where inline images are needed.

**Comment by Dangoo** [comment]
> @tight: inlining block-by-default images is much more annoying and requires a class or fragile selectors

Might be pointing the stupid obvious, but what stands in the way of using `display: inline-block` as a default? On the one hand side it would remain inline and not break existing behavior. On the other hand side the block aspect allows for vertical margins and resolves the ugly spacing issue.
What do you think? 🤔 

And thats what a [working draft of the spec](http://w3c.github.io/html-reference/img.html#img-display) mentions as "typical default"
```css
img { display: inline-block; }
```

**Comment by tigt** [comment]
@Dangoo I’d be fine with that too, but I think `inline-block` still has the gap in question unless `vertical-align` is also set.

**Comment by jensimmons** [comment]
Just to be clear, this is not a discussion about changing the CSS specification or how browsers work. It is impossible to do so. 

This is about CSS Remedy. If you don’t know what that is, please read the project page for this repo.

**Comment by tigt** [comment]
@jensimmons I’m sorry I was unclear. I’d like to keep `display:inline/inline-block` for ease of development with the aforementioned use-cases, even with Remedy applied.

**Comment by jensimmons** [comment]
Thanks everyone for the input here. It's really fun to take a deep dive into such details, and try to figure out what the 'best' way, the best 'new default' for CSS could be. 

I also posted this question to Twitter, where a _lot_ of people responded. https://twitter.com/jensimmons/status/1094731679040712707

I'd been leaning towards `img { display: block; }` for a while... but the outcry on Twitter asking for `block` decided it for me. There are definitely good reasons to go with the other options. But blockifying images is the most common use case. 

It's not surprising we don't all agree. That's the beautiful thing about having a starter-file, each of us can fork it and make it perfect for our particular way of doing things. Or override the default, setting things back to inline. 

I'm going to close this issue now, I think we've uncovered all the important ideas in this conversation.

**Comment by fantasai** [comment]
@jensimmons Put `img, canvas, object, etc. { display: block; vertical-align: middle; }`. That way it'll be block by default, which makes the most sense, but when someone turns an image inline, it'll default to middle alignment, which is most likely the one that's wanted for that use case.

**Comment by fantasai** [comment]
@Dangoo Images are replaced elements, so `inline` and `inline-block` mean the same thing. (The `block` part of `inline-block` refers to how the element's insides are laid out, and for images CSS can't control that anyway.)

**Comment by uandco** [comment]
I agree on `display: block`, but you kept the `vertical-align: bottom`, is that in case you want to set the image back to `inline`? Seems like belt and braces now.

**Comment by jensimmons** [comment]
I did put `vertical-align: bottom;` in there for the folks who were saying (on Twitter) they struggle when resetting block back to inline. Of course a savvy developer would understand they should adjust the vertical-align, but well, most of us aren't that savvy. 

Fantasai makes a good point, that it's likely people will want `vertical-align: middle in that case`. I'll change it to that. And yes, we should do this for all (?) replaced elements that are inline by default.

@fantasai are all replaced elements inline by default??

So what should we include here?
```
img, video, canvas, audio, iframe, embed, object  { display: block; vertical-align: middle; }
```

SVG?

Ok... lemme go [look this up](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Phrasing_content):

Phrasing content: 
 <abbr>, <audio>, <b>, <bdo>, <br>, <button>, <canvas>, <cite>, <code>, <command>, <data>, <datalist>, <dfn>, <em>, <embed>, <i>, <iframe>, <img>, <input>, <kbd>, <keygen>, <label>, <mark>, <math>, <meter>, <noscript>, <object>, <output>, <progress>, <q>, <ruby>, <samp>, <script>, <select>, <small>, <span>, <strong>, <sub>, <sup>, <svg>, <textarea>, <time>, <var>, <video>, <wbr> 

Embedded content: 
<audio>, <canvas>, <embed>, <iframe>, <img>, <math>, <object>, <svg>, <video>

**Comment by fantasai** [comment]
See https://html.spec.whatwg.org/multipage/rendering.html#replaced-elements

**Comment by uandco** [comment]
I would still choose a camp and go `display: block` only, then let the ones that want to reset it back to `inline` deal with the alignment themselves, depending on their need.

**Comment by TalbotG** [comment]
**img {vertical-align: text-bottom;}**
will put images at descent's position. img {vertical-align: text-bottom;} is what I propose.
The issue or problem you want to fix has everything to do with vertical-alignment, not with default display of images inside a line box.
By default, img are vertically-positioned at alphabetic baseline.
Demontrations:
http://www.gtalbot.org/DHTMLSection/vertical-align-values.html
http://www.gtalbot.org/DHTMLSection/vertical-align-values-dhtml.html

**Comment by uandco** [comment]
> The issue or problem you want to fix has everything to do with vertical-alignment, not with default 'display' of  inside a line box.

What this is trying to fix is the gap you get between images when you stack them, not how images are aligned with text when kept inline.

**Comment by TalbotG** [comment]
Blockifying an `<img>` just to adjust an image's vertical position within a line box seems to me like a misadapted pure force attempt to "correct" matters. If you understand line box, inline formating, etc..., then you won't use `display: block` on `img`

**Comment by TalbotG** [comment]
The gap between stacked images is due to default alphabetical baseline-alignment of images inside line boxes.

**Comment by uandco** [comment]
> Blockifying an `<img>` just to adjust an image's vertical position within a line box

That's not the goal here. The discussion is about solving the problem for 90% of the cases, and 90% of the time, your images will be block elements, and if you revert some back to inline, then have a vertical-align fallback.

**Comment by TalbotG** [comment]
When people do not understand how inline formating, line box and vertical-align positioning work, then they resort to all kinds of radical and pure-force hacks like `display: block`, `padding-bottom`, `margin-bottom`, etc...

**Comment by uandco** [comment]
`display: block` on images in 2019 is not a hack, it's convenience.

**Comment by TalbotG** [comment]
You do not understand, me, uandco.

Maybe the following pages and demos - that I did not write - will help you understand what I've been trying to explain to you:

http://dorayme.netweaver.com.au/alt/inlinePicWithDescenderSpace.html

http://www.d.umn.edu/~lcarlson/csswork/inline/inline_images.html

https://web.archive.org/web/20140319193802/http://www.maxdesign.com.au/articles/vertical-align/

**Comment by uandco** [comment]
> You do not understand, me, uandco.

Trust me I do, and everybody does here, but I don't think you understand modern web design.

**Comment by jensimmons** [comment]
@uandco @talbotG 

Hey, both of you, stop this. This project is not going to be a place for adversarial bickering. You’ve each advocated for your position. Now stop. No insulting each other.

**Comment by eallenOP** [comment]
I am teaching Web Intro this semester and last week I had a class on inline vs block... I literally thought that images were already block for a moment there so I'm voting for that to be the remedy. In my mind it's what they are anyway.

**Comment by adamwathan** [comment]
For the curious out there (like me!) do you mind explaining why it makes sense to add this rule just for `img` and `video` but not for the other replaced elements?

```css
img, video {
  max-width: 100%; /* Make images and video flexible by default. */
  height: auto; /* Ensure images and video maintain their aspect ratio when max-width comes into play. */
}
```

Working on improving our base styles for [Tailwind](https://github.com/tailwindcss/tailwindcss) and learning a lot following the meticulous work in this project 👍

**Comment by pxwee5** [comment]
With this implementation where img and svg are blocks, how do we do stuff like:
```
<a href="google.com"> // Full width of 375px
  <img src="myimage.png" width="100" style="margin: auto;"> // set to be 100px width
</a>
```
Instead of linking your image only, you're now linking the whole section (the 275px outside of the image).

How would you handle this?

**Comment by mirisuzanne** [comment]
After some testing, I propose:

```css
/*
* 1. Block display is usually what we want
* 2. Remove strange space-below when inline
* 3. Responsive by default
*/
img, svg, video, canvas, audio, iframe, embed, object {
  display: block;
  vertical-align: middle;
  max-width: 100%;
}

/* 
* Maintain intrinsic aspect ratios when `max-width` is applied 
* (audio, iframe, embed, and object have no intrinsic ratios, set height explicitly)
*/
img, svg, video, canvas {
  height: auto;
}
```

**Comment by tigt** [comment]
I ran into an issue recently with `img { vertical-align: middle }` at work.

If an image breaks and falls back to its `alt` text, a `vertical-align` other than `baseline` produces different behavior across browsers. [Here’s a CodePen to demonstrate.](https://codepen.io/tigt/pen/f64a5ca1ebbcc85628ed0491040c74ef)

* Older (current?) versions of Firefox have the `alt` text dip below the baseline
* As of Firefox Nightly 71.0a1, though, the changing of `vertical-align` appears to be ignored and the text flows on the same baseline, which seems ideal to me.
* Chrome has the same problem as older Firefox, along with a broken image icon

Is it worth trying to fix this problem with selectors specifically for `alt` text? (Like `img:is(:-moz-broken, :-moz-loading, :-moz-user-disabled)`)

**Comment by mirisuzanne** [comment]
@tigt Maybe open that as a new issue for discussion? I'm not sure how high priority that should be, but I'm interested in hearing people's thoughts.

**Comment by web2033** [comment]
```css
img,
svg,
video,
canvas,
audio,
iframe,
embed,
object {
  display: block;
  vertical-align: middle;
}
```
VS Code prompts this warning: 
`Property is ignored due to the display. With 'display: block', vertical-align should not be used.`

**Comment by Sora2455** [comment]
@web2033 Read the earlier comments - the vertical-align is there so that when people change their images to inline with an override style, the tiny gap under them is still gone by default.

The rule is basically "Block by default, vertical-align middle if not block".

**Comment by BassOfBass** [comment]
Just add a comment above `vertical align` stating it's a fallback value for inlines.

**Comment by lautapercuspain** [comment]
> ```css
>  max-width: 100%; 
> ```

Hey @adamwathan , I just wanted to let you know that `max-width: 100%;` as default on an `image` element, breaks a development that relies on transform and translate3d, to move the focus point of the specific image into the inside a wrapper. 
When I remove `max-width: 100%; ` from the **img** element, it works as expected.

**Comment by tranvansang** [comment]
It took me several hours to figure out that there is no bug in my library, just the default `max-width: 100%` comes from tailwind causes my layout to break.

I believe that setting the layout of the img elements by the parent width is a bit too opinionated. It is perfect if there is an option to disable this.

**Comment by BassOfBass** [comment]
> I believe that setting the layout of the img elements by the parent width is a bit too opinionated. It is perfect if there is an option to disable this.
Using `<img>` outside of wrapper element IS the opinionated approach though, since replaceable elements behave inconsistently between browsers, especially when they are the part of flexbox/grid.

**Comment by Imagoenlight** [comment]
> I was just reading Tantek's original [Reset stylesheet](http://tantek.com/log/2004/undohtml.css) (likely the first ever).
> 
> He wrote
> 
> ```
> /* whoever thought blue linked image borders were a good idea? */
> a img,:link img,:visited img { border:none }
> ```
> 
> OMG! That's right. There were ugly blue boxes around images that have a link. Does this still happen anyplace? I don't think so. But if it does.... we should fix it. Ha.
> 
> Meanwhile, I do think images still have that little gap below them, because they are `display: inline` by default (mistake, imho), and the line height for whatever text size is added to the bottom of the box. I've spent many hours of my life trying to figure out where that gap is coming from. Until I finally remembered to always include this in my CSS:
> 
> ```
> img { display: block; }
> ```
> 
> Shall we add that to Remedy? Does anyone else always do this?



> I was just reading Tantek's original [Reset stylesheet](http://tantek.com/log/2004/undohtml.css) (likely the first ever).
> 
> He wrote
> 
> ```
> /* whoever thought blue linked image borders were a good idea? */
> a img,:link img,:visited img { border:none }
> ```
> 
> OMG! That's right. There were ugly blue boxes around images that have a link. Does this still happen anyplace? I don't think so. But if it does.... we should fix it. Ha.
> 
> Meanwhile, I do think images still have that little gap below them, because they are `display: inline` by default (mistake, imho), and the line height for whatever text size is added to the bottom of the box. I've spent many hours of my life trying to figure out where that gap is coming from. Until I finally remembered to always include this in my CSS:
> 
> ```
> img { display: block; }
> ```
> 
> Shall we add that to Remedy? Does anyone else always do this?



> I was just reading Tantek's original [Reset stylesheet](http://tantek.com/log/2004/undohtml.css) (likely the first ever).
> 
> He wrote
> 
> ```
> /* whoever thought blue linked image borders were a good idea? */
> a img,:link img,:visited img { border:none }
> ```
> 
> OMG! That's right. There were ugly blue boxes around images that have a link. Does this still happen anyplace? I don't think so. But if it does.... we should fix it. Ha.
> 
> Meanwhile, I do think images still have that little gap below them, because they are `display: inline` by default (mistake, imho), and the line height for whatever text size is added to the bottom of the box. I've spent many hours of my life trying to figure out where that gap is coming from. Until I finally remembered to always include this in my CSS:
> 
> ```
> img { display: block; }
> ```
> 
> Shall we add that to Remedy? Does anyone else always do this?

Hello, can I talk with you about something that starts with cic8...

**Comment by MorningLit** [comment]
Not sure if anyone is also facing tons of warnings from using Next.js with TailwindCSS (tailwind uses preflight), but with these settings on images,
```
img, video {
    max-width: 100%;
    height: auto;
}
```
it causes images to be "responsive" based on the image's height, which can be ideal for some developers. 

However, Next.js has some optimisations for images built in-place and it needs images to be explicitly set a width and a height, so I'm unsure which option to follow. 
I'm slightly leaning onto Next.js's side, because these settings tend to produce unexpected results if your picture is in portrait mode and you have already set a desired height for it. (The image will overflow the height that you have set)
Even after reading this thread, I can't really find a compelling reason to use this CSS rule as a form of CSS reset.
```
img, video {
  max-width: none;
  height: revert-layer;
}
```

Here's what I did to revert the changes for this CSS rule. (By also explicitly defining width and height on the <img/> tag) You might also want to add `object-fit: contain` to prevent the stretching of images. 

Relevant thread where people are also facing a similar issue: https://github.com/tailwindlabs/tailwindcss/issues/506
Would recommend to reopen this issue again and discuss it
