### ISSUE TITLE
Attribution Question

### ISSUE THREAD

**Issue by blakeprudhomme** [mozdevs/cssremedy#22]
This is more of a question than an issue:

I just set this up as a [ruby gem](https://rubygems.org/gems/cssremedy-rails).

I'd like to give proper attribution on https://github.com/blakeprudhomme/cssremedy-rails.

Can someone please advise if there is a more specific credit I should put other than "Mozilla Developer Outreach."

**Comment by jensimmons** [comment]
There are a lot of people contributing by discussing this project in the issues.
https://github.com/mozdevs/cssremedy/issues

And some of those folks are showing up in the Git Commits.
https://github.com/mozdevs/cssremedy/graphs/contributors
(Although being on a commit is not a good measure of involvement. Never mind influence.)

We have a ways to go until this is ready for release. It's hard to predict who else will be involved by the time we get there. 

That said, this project was started by and is being led my me, Jen Simmons, @jensimmons. I work for Mozilla Developer Outreach.
