### ISSUE TITLE
Document level flag for modern defaults

### ISSUE THREAD

**Issue by tobz-nz** [mozdevs/cssremedy#23]
Could there be a document level setting to change the default styles to a more modern set?
Similar to setting the HTML5 doctype? `<!DOCTYPE html>`

A simple flag maybe? `<!DOCTYPE html modern>` as a _terrible_ example.
Then maybe we could have nice things.

**Comment by jensimmons** [comment]
Yes, this could be done. 

I should refine the story of CSS Remedy, so it's not confusing. That's true, browsers could "pay off technical debt" by doing exactly what we did last time this was a big problem, creating a new doctype.

That said, I can't see that happening anytime soon. I'm not sure that there's enough technical debt, or enough of a reason. I see that there is enough such pain for a new starter file to be helpful. I'm not sure it's painful enough for browsers to make such a doctype.

THAT said, let's see what happens with this project. If Remedy gets complex enough or weird enough, that could help the Working Groups realize, "oh maybe we should solve this in the browsers".... for now, I expect the Working Groups will be like "eh, it's not that bad. Authors can just deal with it in their CSS."

**Comment by frivoal** [comment]
This relates to https://wiki.csswg.org/faq#versioning-css-fixing-design-mistakes
