### ISSUE TITLE
img without height definition ignore aspect ratio

### ISSUE THREAD

**Issue by lauriemustafic** [mozdevs/cssremedy#25]
By not defining `height: auto;`, images do not maintain their aspect ratio due to max-width:100%;

[codepen example](https://codepen.io/lauriemustafic/pen/MLGBVe/left/)

**Comment by jensimmons** [comment]
Ah, yup. This isn't a problem if there's no height specified for the image in HTML, but if there is, that height overrides the browser default of auto height. We need to override the override, and reset it to auto. Thanks. And thanks for making the demo / test.
