### ISSUE TITLE
CSS contains git merge output

### ISSUE THREAD

**Issue by dan1elhughes** [mozdevs/cssremedy#31]
Heya! I noticed the CSS file contains git merge resolution output. https://github.com/mozdevs/cssremedy/blob/master/remedy.css#L64-L67

It was added in [this commit](https://github.com/mozdevs/cssremedy/commit/c3fead2cd85dc57207ddfd9058cfda2373e1333a).

**Comment by jensimmons** [comment]
Thanks! It should be fixed now.
