### ISSUE TITLE
In a component world are resets needed at all?

### ISSUE THREAD

**Issue by tomgenoni** [mozdevs/cssremedy#37]
One of the not-yet-realized promises of using web components is the confidence that a component will render as expected in any context. This means its styles will be insulated from, and won't leak to, surrounding components. For example, if I create a `<Button>` component the hope is that each consumer — websites in my company or third-party sites we integrate with — will be able import and render it. 

The problem with resets is that they become external dependencies that both must exist and must exist in a certain order. If to use my `<Button>` component you have to also use my reset, someone's code is very likely going to get clobbered.

Wouldn't a better solution be to move element resets into their respective components? With this approach whatever was needed by `<Button>` would be contained in the `<Button>` component, likewise for tables, lists, headings. The only CSS that maybe wouldn't fit into this model is the global `box-sizing` reset `*, ::before, ::after { box-sizing: border-box; }` rule but potentially that, too, could be included by any components that needed it. 

If you're using "naked" HTML clearly this approach won't work and a reset is useful. But I wonder if long-term we should aim for less reliance on global dependencies as web components become the standard.

**Comment by meyerweb** [comment]
Remedy is not a reset, and is specifically focused on HTML, so I’m unclear on the purpose of your post.

**Comment by tomgenoni** [comment]
I intended to use "reset" generically to refer to any CSS that sets root styles. I suppose for my purposes we could call it an "opinionated dependency". 

In any case the purpose of my post was, hopefully, to start a discussion about the future of this type of approach given the popularity / inevitability of web components. But If you don't think it's appropriate here you can close.

**Comment by nternetinspired** [comment]
> …given the popularity / inevitability of web components

That is a very subjective viewpoint. Personally, I don't see web components as either popular or inevitable.

HTML and CSS on the other hand are undeniably popular and will I suspect continue to be so for a very long time yet.

**Comment by tomgenoni** [comment]
By "popularity / inevitability of web components" I meant any technology using the concept of encapsulated components. This includes React, Vue, Ember, and eventually native "vanilla" web components (aspects of which already have browser support). 

I should add that this post is neither a knock on this project nor of HTML/CSS. The output of the above technologies is HTML/CSS and will be for along time. My interest has for years been exploring ways of managing all of it, particularly CSS, at scale.
