### ISSUE TITLE
What does `:root:lang(x), :not(:lang(x)) > :lang(x)` catch that `lang(x)` doesn’t?

### ISSUE THREAD

**Issue by tigt** [mozdevs/cssremedy#54]
I see that [the source from the HTML spec](https://html.spec.whatwg.org/multipage/rendering.html#quotes) is autogenerated, but the [source code what does that generation](https://github.com/whatwg/html-build/tree/master/quotes) doesn’t indicate why these particular selectors. The Git history for [the line that generates the selectors](https://github.com/whatwg/html-build/blob/4c7a8ed6a70394857271a15d1189288628a2652b/quotes/cldr-processor.pl#L38) ends with the initial move to GitHub, so I couldn’t find any historical context.

The `:not(:lang(x)) > :lang(x)` selectors seem like they could be expensive, so I’m interested in why they exist. Is it a source order thing? What does…

```css
:root:lang(en),
:not(:lang(en)) > :lang(en)
```

…select that `:lang(en)` doesn’t?

**Comment by tigt** [comment]
It struck me that it might be a legacy design decision from before the `:lang()` pseudo-class existed. If you had to use attribute selectors, then the following works around some issues with nested languages:

```css
:root[lang^=en],
:not([lang^=en]) > [lang^=en]
```

If this is the case, it might be possible to simplify the suggested styles in the HTML Standard, as well.

**Comment by tigt** [comment]
Whoops, looks like [I already brought this up in #6](https://github.com/mozdevs/cssremedy/issues/6#issuecomment-462192833). Sorry about that. Should I close this issue?

**Comment by mirisuzanne** [comment]
on it, thanks!
